### ISSUE TITLE
Empty response when sending order 

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/api#1]
When send the order via `POST api.lunches.com.ua/orders` with Body: 

``` json
{
    "items": [{
        "size": "big",
        "quantity": "2",
        "productId": "1",
        "date": "2016-07-03"
    }, {
        "productId": "2",
        "date": "2016-07-05"
    }, {
        "productId": "1",
        "date": "2016-07-04",
        "size": "small"
    }],
    "customer": "\u0421\u0435\u0440\u0433\u0435\u0439"
}
```

I get empty json string `{}` with status 201 

I'm assume that body should not be empty.

**Comment by warlock39** [comment]
It is expected behavior. To get created order, you should run http GET request to url that specified in Location http header. 
But thanks for your notice, response should be completely empty instead of {}

**Comment by dezoxel** [comment]
@warlock39 Please take a look at http spec here: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html. Refer to "10.2.2 201 Created" paragraph. Quoting: 

> The response SHOULD include an entity containing a list of resource characteristics and location(s) from which the user or user agent can choose the one most appropriate

There are also additional requirements for body content.

**Comment by warlock39** [comment]
@dezoxel , this specification defines recommendations but not restrictions. It is common pattern to include or not include newly created entity in response body. If it is useful for API clients to read contents from response body, i can include it. In some cases, clients do not need response, just create and leave. For the ones clients it will additional network traffic consumed (actually, our case is the same). There are many API clients can be, but API is only one, so empty response body is more common approach. 
If you really need body content, i will include it. You decision?

**Comment by dezoxel** [comment]
@warlock39 lets include entity when it is needed at least in one, first case. Leave empty as for now. @Kostya47 correct behavior for now is to return _empty_ body, not `{}`. If it is empty for now - lets close the issue

**Comment by Kostya47** [comment]
Issue still present.

**Comment by warlock39** [comment]
Done

**Comment by dezoxel** [comment]
@warlock39 as we turned out recently, we do need an entity in the response. After user have placed his order, he receives toast notification about status (ok/fail). When order is placed successfully it would be good to the link to newly created order in the toast message.

**Comment by warlock39** [comment]
@dezoxel , we have misunderstanding. Can you provide more detailed description about api client requirements for order creation API response ? Do we need an entity in the response in any case?

**Comment by dezoxel** [comment]
@warlock39 Yes, we need an entity in the response. Please implement.

**Comment by warlock39** [comment]
@Kostya47 , done

**Comment by Kostya47** [comment]
Good work! Closed.
