### ISSUE TITLE
Add `paymentDate` to transaction

### ISSUE THREAD

**Issue by dezoxel** [lunches-platform/api#105]
It is needed for a case when transaction create date differs from real money income date.

**Comment by warlock39** [comment]
@dezoxel , so why do we need to create transaction in that case?

**Comment by dezoxel** [comment]
@warlock39 I am not sure I correctly understand you. Lets see an example:
- We can see sms message about payment from client, but we can't create transaction manually now by any reason. We decided to create transaction tomorrow. In this case actual transaction create date will not equal actual transaction date from user.
- Just for such case we will enter `paymentDate` field manually (current day by default).

**Comment by warlock39** [comment]
@Kostya47 , please test

**Comment by Kostya47** [comment]
Verified.
