### ISSUE TITLE
Need ability to distinguish meat and fish

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/api#121]

**Comment by Kostya47** [comment]
I assigned `type` **fish** for corresponding products.

**Comment by warlock39** [comment]
What is the intention ?

**Comment by dezoxel** [comment]
@warlock39 it is required for automatic prices filling. We have different prices for meat and fish lunches. Currently I don't have ability to distinguish products by meat and fish, thus, I can't fill in prices for fish.

**Comment by warlock39** [comment]
@dezoxel , please describe algorithm of how you are going to automate price filling.

**Comment by dezoxel** [comment]
@warlock39 
1. Fetch two week menu: current and next.
2. Define the hashmap of all prices: 

```
{
  ...,
  'meat-big|garnish-big|salad-big': 70,
  'fish-big|garnish-big|salad-big': 90,
  ...
}
```
1. Go by menus.
2. Create the list of priceGroups for each menu products combination.
3. Get the price for each priceGroup by defining key like `meat-big|garnish-big...`
4. Send the priceGroup to API

**Comment by warlock39** [comment]
@dezoxel thank you. Why `product.type` field doesn't solve this problem?

**Comment by dezoxel** [comment]
@warlock39 I'm trying to use only `product.type`. Lets see how it works. I'll notify you later

**Comment by warlock39** [comment]
@dezoxel what is your resolution?

**Comment by dezoxel** [comment]
@warlock39 works just fine, issue could be closed
