### ISSUE TITLE
Reject Orders

### ISSUE THREAD

**Issue by warlock39** [lunches-platform/api#124]
- Orders can be rejected only by admins. 
- Rejection differs from cancelation by the role who performs it, and by the reason. 
- Orders are rejected when it was fail from Lunches. 
- Orders rejections is usually performs when order is delivered, but such orders should not be paid.
- When order is paid, refund should be performed. 
- Rejected (or canceled) order can not be paid.

```
POST /orders/37/reject HTTP/1.1
Content-Type: application/json
Host: 

{"reason":"Hair in the food"}
```

**Comment by warlock39** [comment]
@Kostya47 , please test

**Comment by Kostya47** [comment]
Verified.
