### ISSUE TITLE
Use environment config

### ISSUE THREAD

**Issue by warlock39** [lunches-platform/api#126]
- admin accessToken
- DB auth params

**Comment by warlock39** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;WXIVmSq2&#x2F;84-126-use-environment-config"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #126 Use environment config</a>

**Comment by warlock39** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;WXIVmSq2&#x2F;84-126-use-environment-config"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #126 Use environment config</a>

**Comment by warlock39** [comment]
@Kostya47 , please test

**Comment by Kostya47** [comment]
@warlock39 What I got:
`POST` `api.qa.lunches.com.ua/transaction?accessToken=[valid access token]`
`{"username":"Yuriy Buchchenko","type":"income","amount":"3000"}`

Comes **404** `{
  "errMsg": "Server error"
}`

**Comment by warlock39** [comment]
@Kostya47 , to get valid HTTP requests please refer to: https://github.com/lunches-platform/api/issues/81
In your case, by some reason, request query path doesn't end on `s`.

**Comment by Kostya47** [comment]
Thanks for help. Now I get: `{
  "message": "There is no such user"
}`, when I add to body any existing username (or also not existing)

**Comment by warlock39** [comment]
Hm, try to use this one: `Josh Miller` as the username

**Comment by Kostya47** [comment]
Same error `{ "message": "There is no such user" }`

**Comment by warlock39** [comment]
Are you sure that you are running at QA server? It seems you make request to prod server, where this user certainly non exists.

**Comment by Kostya47** [comment]
Source message:

```
POST /transaction?accessToken=86640********************474209b792 HTTP/1.1
HOST: api.qa.lunches.com.ua
content-type: application/json
content-length: 59

{"username":"Max Golionko","type":"income","amount":"2500"}
```

**Comment by warlock39** [comment]
@Kostya47 , same as 7 days ago [you forgot `s` char after `POST /transaction`](https://github.com/lunches-platform/api/issues/126#issuecomment-243748012)

**Comment by Kostya47** [comment]
@warlock39 Sorry, I'm used request from history in my REST client and it has made some confusion. Closed.
