### ISSUE TITLE
Optimize images traffic usage

### ISSUE THREAD

**Issue by warlock39** [lunches-platform/api#128]
We use raw product images now to display to users. Cloudinary (out images hosting provider) has brilliant CDN to deliver web-optimized images. This issue is intended to properly use cloudinary API.

**Comment by warlock39** [comment]
@Kostya47 , quality of images should be decreased but image size is decreased too. Previously each image has about 30Kb. Please test.

**Comment by Kostya47** [comment]
@warlock39 Need to re-upload all existing images?

**Comment by warlock39** [comment]
@kostya47, no, you shouldn't

**Comment by Kostya47** [comment]
Verified.
