### ISSUE TITLE
Update cover of a product API

### ISSUE THREAD

**Issue by warlock39** [lunches-platform/api#129]
It can be only one cover within product images.

```
PUT /products/12/images/cnm8fyqryzumimaatsk5/cover HTTP/1.1
Content-Type: application/json
Host: api.qa.lunches.com.ua
```

**Comment by warlock39** [comment]
@Kostya47 , it can be tested

**Comment by Kostya47** [comment]
@warlock39 Return _204: No Content_ with such request:

```
PUT /products/12/images/cnm8fyqryzumimaatsk5/cover HTTP/1.1
HOST: api.qa.lunches.com.ua
content-type: application/json
content-length: 0
```

**Comment by Kostya47** [comment]
There is also problem when i tried to set cover for product which is already assigned image, but I get this response: `{
"message": "Such image is not assigned to this product"
}`

**Comment by warlock39** [comment]
@Kostya47 

> Return 204: No Content 

`2**` family of HTTP status codes is OK

> There is also problem when i tried to set cover for product which is already assigned image

Could you provide HTTP request?

**Comment by Kostya47** [comment]
I finally figured out in all, thank you. Closed.
