### ISSUE TITLE
Unable to place order error

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/api#136]
**Steps to reproduce:**
1. Open main page.
2. Add at least one product.
3. Go to basket.
4. Fill all required fields.
5. Press "Place order".

**AR:** Order was not placed.
**ER:** Order should be placed.

**Comment by warlock39** [comment]
@Kostya47, please clarify environment preconditions

**Comment by Kostya47** [comment]
iOS 9.3.5;
Google Chrome 53.0.2785.86;
User: Yuriy Buchchenko;
Added to basket: for Friday 9-th of September, one middle ready meal.

Also reproduced this bug on Ubuntu desktop and Android device.

**Comment by warlock39** [comment]
@Kostya47 , fixed. 

Please, specify QA or Prod environment next time.

**Comment by Kostya47** [comment]
Verified.
