### ISSUE TITLE
Missing prices on week menu

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/api#139]
![- mozilla firefox_023](https://cloud.githubusercontent.com/assets/18617219/18542094/a3ca3d10-7b31-11e6-8db8-f921d201b0cb.png)
![- mozilla firefox_022](https://cloud.githubusercontent.com/assets/18617219/18542097/a6893614-7b31-11e6-85a9-8d48068e8f40.png)

**Comment by warlock39** [comment]
@Kostya47 , fixed

**Comment by warlock39** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Ybzff7eS&#x2F;1-missing-prices-on-week-menu-139"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Missing prices on week menu #139</a>

**Comment by Kostya47** [comment]
Verified.
