### ISSUE TITLE
Implement endpoint for getting next week menu

### ISSUE THREAD

**Issue by warlock39** [lunches-platform/api#15]
```
GET /menus/week/next HTTP/1.1
Content-Type: application/json
Host: api.lunches.com.ua
```

**Comment by warlock39** [comment]
@Kostya47 , please test

**Comment by Kostya47** [comment]
@warlock39 We don't have menu for next week in our DB. Also, I can't fill it because aunt Nadia didn't make needed menu. I will test immediately when it becomes possible.

**Comment by Kostya47** [comment]
Verified.
