### ISSUE TITLE
Upload and store images in cloudinary

### ISSUE THREAD

**Issue by warlock39** [lunches-platform/api#16]
Added two new API endpoints:
-     **Get info about early uploaded image by its ID**:

```
GET /images/{imageId} HTTP/1.1
Host: api.lunches.com.ua
```
-   **Upload image**:

```
POST /images HTTP/1.1
Content-Type: multipart/form-data; charset=utf-8; boundary=__BOUNDARY__
Host: api.lunches.com.ua
Content-Length: 326130

--__BOUNDARY__
Content-Disposition: form-data; name="file"; filename="IMG_2016-05-09 15:47:40.jpg"
Content-Type: image/jpeg

**IMAGE DATA**
```

**Comment by warlock39** [comment]
@Kostya47 , please test.

**Comment by Kostya47** [comment]
Works well. Closed.

**Comment by Kostya47** [comment]
@warlock39 Please check.
![scrn_rec-2016-08-26_03 09 49](https://cloud.githubusercontent.com/assets/18617219/17990054/eeb4ecf0-6b3a-11e6-8d70-990a88797397.gif)

**Comment by warlock39** [comment]
@Kostya47 , double check that http query is constructed well. I can't reproduce. 
To ensure http request validity, publish plain http request here

**Comment by dezoxel** [comment]
@warlock39  Doesn't work. Tried `api.qa.lunches.com.ua` and `api.cogniance.lunches.com.ua`. Copying raw HTTP request.

```
POST /images HTTP/1.1
Host: api.qa.lunches.com.ua
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Cache-Control: no-cache
Postman-Token: 1609ba4b-dab2-b578-64a3-d22eb0777624

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name=""; filename=""
Content-Type: 
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

**Comment by dezoxel** [comment]
The same result when using Advanced Rest Client:

```
POST /images HTTP/1.1
 HOST: api.qa.lunches.com.ua
 content-type: multipart/form-data; boundary=----WebKitFormBoundarydo6rsLAXxHaTJJoM
 content-length: 156

 ------WebKitFormBoundarydo6rsLAXxHaTJJoM
 Content-Disposition: form-data; name="fileUpload"

 [object Object]
 ------WebKitFormBoundarydo6rsLAXxHaTJJoM--
```

**Comment by warlock39** [comment]
@dezoxel , @Kostya47 , both of your requests are not valid. In the first case name of query param for file is empty, and in the second case specified param name is invalid. Valid param name is `file`. 
Note, you should not specify needed http headers manually, just leave Postman to do that work. 

So, to make it work you just need to replace `fileUpload` key to `file` key (your second snippet), and everything should work. 
Also, i have added additional check to return 400 error with detailed error message instead of 500.

**Comment by Kostya47** [comment]
It worked with ARC. Request example:

```
POST /images HTTP/1.1
HOST: api.qa.lunches.com.ua
content-type: multipart/form-data; boundary=----WebKitFormBoundary1TiAQsKeoQU8Iw3X
content-length: 54777

------WebKitFormBoundary1TiAQsKeoQU8Iw3X
Content-Disposition: form-data; name="file"; filename="Farshirovanny_perets_s_myasom_i_risom_s_tomatom.jpg"
Content-Type: image/jpeg
```
