### ISSUE TITLE
Assign images to products

### ISSUE THREAD

**Issue by warlock39** [lunches-platform/api#18]
Products don't have images now. 
Menu without images is not a menu. 

Product must have several images. And one image should be a cover. 

To implement such functionality we will express next API endpoints:
- **Assign image to product**

```
PUT /products/{productId}/images/{imageId}?cover=1 HTTP 1.1
Content-Type: application/json
Host: api.lunches.com.ua
```
- **Get product images**

```
GET /products/{productId}/images HTTP 1.1
```
- **Get products with images**

```
GET /products?images=1 HTTP 1.1
```

`images=1` by default

When API requests send to `/menus` endpoint, the same rules is applied as mentioned above.

**Comment by warlock39** [comment]
@Kostya47 , please test

**Comment by Kostya47** [comment]
Done. Closed.
