### ISSUE TITLE
Unlimited product quantity when placing order

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/api#20]
**Steps to reproduce:**
1. Send order `POST api.lunches.com.ua/orders` with _quantity = 150_

```
{
    "items": [{
        "size": "big",
        "quantity": "150",
        "productId": "12",
        "date": "2016-07-15"
    }],
    "customer": "Jack"
}
```

**AR:** Order created.
**ER:** Order should not be created.

**NOTE:** @warlock39 Previously, this requirement was not agreed with you, but on Front-End established max. value of _"quantity" = 100_

**Comment by warlock39** [comment]
@Kostya47 , fixed

**Comment by Kostya47** [comment]
Verified.
