### ISSUE TITLE
Unable to place order error

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/api#22]
**Steps to reproduce:**
1. Go to week order page.
2. Select and add any products.
3. Go to basket.
4. Fill _Name_ and _Address_ fields.
5. Press _"Place order"_ button.
![scrn_rec-2016-07-14_14 21 52](https://cloud.githubusercontent.com/assets/18617219/16838112/32a3535c-49d0-11e6-8525-9fc8c23b1570.gif)

**AR:** `Error! Unable to place order`
**ER:** Order should be created.

**Comment by warlock39** [comment]
@Kostya47 , have you tried to place an order directly without frontend? Error specified in Actual Result is not an actual error from API, it seems frontend error handling doesn't display real error, so i can't reproduce it by your STR.

**Comment by dezoxel** [comment]
@Kostya47 it should fixed already. Please test

**Comment by Kostya47** [comment]
I saw what all work correct. Close when UI will avaliable.

**Comment by Kostya47** [comment]
@dezoxel  Still doesn't work.

**Comment by dezoxel** [comment]
@warlock39 API falls:
Request:

```
{"items":[{"productId":5,"size":"medium","quantity":1},{"productId":27,"size":"medium","quantity":1},{"productId":21,"size":"medium","quantity":1}],"customer":"Yuriy","address":"1","shipmentDate":"2016-07-29"}
```

Response:

```
{"message":"Invalid input data provided","errors":{"address":"Invalid address"}}
```

What kind of validation do you have on your side?

**Comment by warlock39** [comment]
@dezoxel , order address must have two characters or greater and less than 150 characters. I decreased required number of characters to 1, so your request should work correctly now.

**Comment by dezoxel** [comment]
@Kostya47 please test

**Comment by Kostya47** [comment]
Verified.

**Comment by Kostya47** [comment]
@warlock39 Same problem, please fix.

**Comment by warlock39** [comment]
@Kostya47 , can you provide error message from API? As of New pricing model (#39), it is required to have prices in DB to create order, have you filled at least one price for each product? I can guess more, but i think without API error message it is not efficient.

**Comment by Kostya47** [comment]
Prices were filled and made fixes in https://github.com/lunches-platform/fe/issues/121, now works fine. Closed.
