### ISSUE TITLE
Incorrect sorting of products

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/api#32]
**Steps to reproduce:**
1. Go to week menu page.
![fountainjs - google chrome_004](https://cloud.githubusercontent.com/assets/18617219/16988397/057e5926-4e99-11e6-8fad-f97a8ccd755c.png)

**AR:** Incorrect sorting for Friday.
**ER:** Menu for all days must be sorted as follow:
_1. Meat.
2. Garnish.
3. Salad._

**Comment by warlock39** [comment]
@Kostya47 , done. Please note, that sorting will actually be applied when `position` field from `menu_product` db table will have non-zero value. It is great ability to test by changing value of that field. 
I specified values for menu_id=9 as an example

**Comment by Kostya47** [comment]
I understand your idea it's simple and clear decision. I test it when UI will work.

**Comment by dezoxel** [comment]
@Kostya47 you can test it without UI. Just ensure that API returns correct of order of items

**Comment by Kostya47** [comment]
Success, closed.
