### ISSUE TITLE
Address isn't store in DB

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/api#33]
**Steps to reproduce:**
1. Add some products and go to basket.
2. Fill name and floor fields.
3. Press "Place order".
![46 101 185 96 - localhost - lunches - order phpmyadmin 4 0 10deb1 - google chrome_004](https://cloud.githubusercontent.com/assets/18617219/17017809/8e437648-4f3d-11e6-9b64-ad5c180bf2bb.png)

**AR:** Record was not added.
**ER:** Record should be added.

**Comment by warlock39** [comment]
@Kostya47 , done, please test

**Comment by Kostya47** [comment]
Verified.
