### ISSUE TITLE
New pricing model

### ISSUE THREAD

**Issue by warlock39** [lunches-platform/api#39]
New pricing model involves products groups creation and assign single price for it. Such model allows to assign price to products group which less than the price of sum of individual products.  Product group must contain >= 1 product. Each product must be contained at least in one group. 

Next API-endpoint is used to assign price to product(s):

```
PUT /prices/2016-07-29 HTTP/1.1
Content-Type: application/json
Host: api.lunches.com.ua
Content-Length: 119

{
   "price":"55",
   "items":[
      {
         "size":"big",
         "productId":"111"
      },
      {
         "productId":"2",
         "size":"big"
      },
      {
         "productId":"1",
         "size":"big"
      }
   ]
}
```

Note that `PUT` http method is used. It means that operation of price assigning is idempotent. So when you run this request again with the same data, a http response will not changed. Each next request with the same data must not duplicate data in DB.

**Comment by warlock39** [comment]
@Kostya47 , done, please test
@dezoxel , take a look at the request. What do you think about format?

**Comment by dezoxel** [comment]
API endpoint is great!

**Comment by Kostya47** [comment]
@warlock39 Can you please clarify how to test this functionality?

**Comment by warlock39** [comment]
@Kostya47 , i have added endpoint to get prices by specified date: instead of PUT, use GET http request
Examples of test cases/requirements could be:
- price must be numeric
- price can't be negative and too large
- price is required field
- there couldn't be several same prices per day
- price object must have at least one item
- price item must have valid size field
- price item must have existent productId
- duplicated price items should be filtered
- each next http request with the same data must not duplicate data in DB
- date must be valid
- price can't be edited for passed date
- and so on

**Comment by dezoxel** [comment]
@warlock39 I've tried your endpoints for filling up the prices for all groups (14 in total) per day. Its awesome! Everything works great.

**Comment by warlock39** [comment]
@dezoxel , happy to hear that! To reduce amount of human errors, we will automate product combinations generation and copy prices from the previous week, so process will be automated completely

**Comment by Kostya47** [comment]
Confirmed working properly. I'm filled prices till the end of this week. Ticket closed.
