### ISSUE TITLE
Incorrect work of PUT method when updating image

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/api#40]
**Preconditions:**
- Product should already have assigned image.
- You must have id for your uploaded image.

**Steps to reproduce:**
1. Upload new image for any product
![postman_002](https://cloud.githubusercontent.com/assets/18617219/17180209/56c9b948-5424-11e6-84b1-e422e7ef0a29.png)
2. Show assigned images for your id product.
![postman_003](https://cloud.githubusercontent.com/assets/18617219/17180512/66f61cd4-5425-11e6-93e9-300e95ed2666.png)

**AR:** To the product assigned 2 images

```
[
  {
    "url": "http://res.cloudinary.com/df0ff62zx/image/upload/v1469620221/jfbeq6pbjrk1wawzahfv.jpg",
    "isCover": false
  },
  {
    "url": "http://res.cloudinary.com/df0ff62zx/image/upload/v1469626679/l0ashvn7gkomypvva1ok.jpg",
    "isCover": false
  }
]
```

**ER:** It should be assigned only the last one loaded image.

**Comment by warlock39** [comment]
@Kostya47 , it is expected behaviour, please test again

**Comment by Kostya47** [comment]
Verified.
