### ISSUE TITLE
Cancel non paid orders

### ISSUE THREAD

**Issue by dezoxel** [lunches-platform/api#49]
Please add `canceled` field to Order data structure for all API endpoints:

```
POST /orders
```

```
GET /customers/{customerName}/orders
```

Canceling order requirements:
- only from `status=new`, any other status of Order is not allowed
- until shipmentDate (0:00 am)

API endpoint which handles Order cancel:

```
POST /orders/{orderId}/cancel HTTP/1.1
Content-Type: application/json
Host: api.cogniance.lunches.com.ua

{"reason":"non actual"}
```

**Comment by warlock39** [comment]
@Kostya47 , done , please test. Regression of Order creation needed

**Comment by Kostya47** [comment]
Closed.
