### ISSUE TITLE
[My Orders] Add ability to fetch orders by specified date range

### ISSUE THREAD

**Issue by dezoxel** [lunches-platform/api#50]
Fetch orders by specific date range

Head:

```
GET /customers/{customerName}/orders?startDate=2016-01-01&endDate=2016-02-01 HTTP/1.1
Content-Type: application/json
Host: api.cogniance.lunches.com.ua
```

Body:
Keep the same as current

Note: If date range is not specified orders for the three weeks should be fetch: passed, current and next

**Comment by warlock39** [comment]
@dezoxel @Kostya47 , Done.

Note, changed query path part of request, it looks like this now:
`GET /users/{userName}/orders?startDate=2016-01-01&endDate=2016-02-01`

**Comment by Kostya47** [comment]
Verified.
