### ISSUE TITLE
Integrate users with orders

### ISSUE THREAD

**Issue by warlock39** [lunches-platform/api#61]

**Comment by warlock39** [comment]
@Kostya47 , regression for order creation needed.

**Comment by Kostya47** [comment]
Now there is an error when placing a valid order.
![- google chrome_006](https://cloud.githubusercontent.com/assets/18617219/17480111/01efbbca-5d7f-11e6-8a7d-622dac90ce1a.png)
Postman return: _Could not get any response_

**Comment by warlock39** [comment]
@Kostya47 , can you provide more detailed API error? I can't reproduce

**Comment by Kostya47** [comment]
No longer relevant. Closed.
