### ISSUE TITLE
Simple user registration

### ISSUE THREAD

**Issue by warlock39** [lunches-platform/api#63]
Without password, just name and addresss

```
POST /users HTTP/1.1
Content-Type: application/json
Host: api.lunches.com.ua
Content-Length: 42

{"username":"sergey","address":"jitomir"}
```

**Comment by warlock39** [comment]
@Kostya47 , please test

@dezoxel , note, you should use this endpoint when new order is created and there is no such user  registered yet

**Comment by Kostya47** [comment]
Do not work with: `{"username":"Jochen Miller","address":"Brest"}`

Return: `{
  "message": "Registration failed: Invalid User. Username is required"
}`

**Comment by warlock39** [comment]
@Kostya47 , http://api.lunches.com.ua/users/Jochen%20Miller
Are you sure that format of your request is valid?

**Comment by Kostya47** [comment]
I'm sorry, it was my fault. Work correct. Closed.
