### ISSUE TITLE
Incorrect sorting of week-menu

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/api#70]
**Steps to reproduce:**
1. Open http://cogniance.lunches.com.ua/.
2. Switch to next week menu (also can be for current week menu).

**AR:** _Mon > Thu > Tue > Wed > Fri_

**ER:** _Mon > Tue > Wed > Whu > Fri_

**None:** Same problem present for deit menu.

**Comment by warlock39** [comment]
@Kostya47 , done

**Comment by Kostya47** [comment]
Verified.
