### ISSUE TITLE
Prepare env infrastructure for beta release

### ISSUE THREAD

**Issue by dezoxel** [lunches-platform/api#71]
- DB
- Deploy API

http://api.qa.lunches.com.ua
http://api.astrafit.lunches.com.ua

**Comment by warlock39** [comment]
@dezoxel , can you provide credentials (private, not here) and server to which application should be deployed?

**Comment by warlock39** [comment]
@dezoxel , done
@Kostya47 , please test

**Comment by Kostya47** [comment]
Verified.
