### ISSUE TITLE
Start progress of Orders after midnight

### ISSUE THREAD

**Issue by warlock39** [lunches-platform/api#75]
It should be simple cron script that fetches `status=created` orders and starts progress on them

To run cli command, run from project root directory:
`php consoleApp.php order:start-progress`

**Comment by warlock39** [comment]
@Kostya47 , please test

**Comment by Kostya47** [comment]
That's what i got:
![dezoxel localhost -var-www-api qa lunches com ua_014](https://cloud.githubusercontent.com/assets/18617219/17965716/9e87b84e-6ac6-11e6-8192-0fb58e52308b.png)

@warlock39 Can you tell me more details?

**Comment by warlock39** [comment]
@Kostya47 , i updated config. Try again

**Comment by Kostya47** [comment]
Closed.
