### ISSUE TITLE
Accept CORS requests

### ISSUE THREAD

**Issue by warlock39** [lunches-platform/api#8]

**Comment by warlock39** [comment]
@dezoxel you must be interested in this issue

**Comment by dezoxel** [comment]
Still doesn't work

XMLHttpRequest cannot load http://api.lunches.com.ua/orders. Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by dezoxel** [comment]
Request URL:http://api.lunches.com.ua/orders
Request Method:OPTIONS
Status Code:204 No Content
Remote Address:46.101.185.96:80

**Comment by dezoxel** [comment]
Accept:_/_
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,ru;q=0.6,uk;q=0.4
Access-Control-Request-Headers:accept, content-type
Access-Control-Request-Method:POST
Cache-Control:no-cache
Connection:keep-alive
Host:api.lunches.com.ua
Origin:http://localhost:3000
Pragma:no-cache
Referer:http://localhost:3000/basket
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by warlock39** [comment]
@dezoxel , updated restrictions. Please verify

**Comment by dezoxel** [comment]
@warlock39 works fine, closing
