### ISSUE TITLE
Delete "size_weight" table

### ISSUE THREAD

**Issue by Kostya47** [lunches-platform/api#86]

**Comment by Kostya47** [comment]
@warlock39 https://github.com/lunches-platform/api/issues/85#issuecomment-239678839

**Comment by warlock39** [comment]
@Kostya47 , done

**Comment by dezoxel** [comment]
@warlock39 table still exists. Please remove

**Comment by warlock39** [comment]
Done at QA server.
@Kostya47 , please remind me to delete table on production server when issue are going to be closed
